"""
Device & camera hub: register pluggable inputs (CCTV cameras, IoT sensors) per facility,
test their connectivity, and ingest sensor readings over a one-POST JSON API.

Cameras: source_type webcam (an OS device index), rtsp (a stream URL), or file (a demo
clip). "Test connection" actually opens the source with OpenCV and returns a snapshot,
so device health on the Devices page reflects reality, not registration state.

Sensors: external hardware POSTs {device_id, value} to /iot/readings -- the deliberately
minimal contract that makes any PLC gateway/ESP32/phone scriptable against this in one
line of curl. Devices with source_type "simulated" get readings generated by a background
thread (see start_simulator) so the demo shows live-moving data without real hardware.
"""
from __future__ import annotations

import base64
import threading
import time
import uuid
from datetime import datetime, timedelta

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from db.models import Device, Facility, SensorReading, Zone
from db.session import SessionLocal, get_db

router = APIRouter(tags=["devices"])

DEMO_FACILITY_NAME = "Demo Steel & Chemical Plant"

# A sensor that hasn't reported for this long shows as offline.
SENSOR_STALE_AFTER = timedelta(seconds=120)


def _resolve_facility_id(db: Session, facility_id: str | None) -> uuid.UUID:
    if facility_id:
        return uuid.UUID(facility_id)
    facility = db.query(Facility).filter_by(name=DEMO_FACILITY_NAME).first()
    if facility is None:
        raise HTTPException(status_code=500, detail="No facility seeded -- run `python -m db.seed` first")
    return facility.id


def _device_payload(d: Device, latest: SensorReading | None = None) -> dict:
    return {
        "id": str(d.id),
        "name": d.name,
        "kind": d.kind,
        "source_type": d.source_type,
        "source": d.source,
        "metric": d.metric,
        "unit": d.unit,
        "zone": d.zone.key if d.zone else None,
        "zone_label": d.zone.label if d.zone else None,
        "status": d.status,
        "last_seen": d.last_seen.isoformat() + "Z" if d.last_seen else None,
        "last_error": d.last_error,
        "latest_value": latest.value if latest else None,
        "latest_at": latest.created_at.isoformat() + "Z" if latest else None,
    }


class DeviceCreate(BaseModel):
    name: str
    kind: str  # camera | sensor
    source_type: str  # webcam | rtsp | file | push | simulated
    source: str | None = None
    metric: str | None = None
    unit: str | None = None
    zone: str | None = None


@router.get("/devices")
def list_devices(facility_id: str | None = None, db: Session = Depends(get_db)):
    fid = _resolve_facility_id(db, facility_id)
    devices = db.query(Device).filter_by(facility_id=fid).order_by(Device.created_at).all()
    out = []
    for d in devices:
        latest = None
        if d.kind == "sensor":
            latest = (db.query(SensorReading).filter_by(device_id=d.id)
                      .order_by(SensorReading.created_at.desc()).first())
            # Sensor health is defined by data freshness, not by the last manual test.
            if latest and datetime.utcnow() - latest.created_at < SENSOR_STALE_AFTER:
                d.status = "online"
            elif latest:
                d.status = "offline"
        out.append(_device_payload(d, latest))
    db.commit()
    return out


@router.post("/devices")
def create_device(body: DeviceCreate, facility_id: str | None = None, db: Session = Depends(get_db)):
    fid = _resolve_facility_id(db, facility_id)
    if body.kind not in ("camera", "sensor"):
        raise HTTPException(status_code=400, detail="kind must be 'camera' or 'sensor'")
    if body.source_type not in ("webcam", "rtsp", "file", "push", "simulated"):
        raise HTTPException(status_code=400, detail="unknown source_type")
    zone = None
    if body.zone:
        zone = db.query(Zone).filter_by(facility_id=fid, key=body.zone).one_or_none()
        if zone is None:
            raise HTTPException(status_code=404, detail=f"zone {body.zone} not found")
    device = Device(
        facility_id=fid, zone_id=zone.id if zone else None, name=body.name, kind=body.kind,
        source_type=body.source_type, source=body.source, metric=body.metric, unit=body.unit,
    )
    db.add(device)
    db.commit()
    db.refresh(device)
    return _device_payload(device)


@router.delete("/devices/{device_id}")
def delete_device(device_id: str, db: Session = Depends(get_db)):
    device = db.query(Device).filter_by(id=uuid.UUID(device_id)).one_or_none()
    if device is None:
        raise HTTPException(status_code=404, detail="device not found")
    db.query(SensorReading).filter_by(device_id=device.id).delete()
    db.delete(device)
    db.commit()
    return {"deleted": True}


@router.post("/devices/{device_id}/test")
def test_device(device_id: str, db: Session = Depends(get_db)):
    """Actually try the device. Cameras: open the source with OpenCV, grab one frame,
    return it as a small base64 snapshot with the measured open+read latency. Sensors:
    report freshness of the most recent reading."""
    device = db.query(Device).filter_by(id=uuid.UUID(device_id)).one_or_none()
    if device is None:
        raise HTTPException(status_code=404, detail="device not found")

    if device.kind == "sensor":
        latest = (db.query(SensorReading).filter_by(device_id=device.id)
                  .order_by(SensorReading.created_at.desc()).first())
        fresh = latest is not None and datetime.utcnow() - latest.created_at < SENSOR_STALE_AFTER
        device.status = "online" if fresh else "offline"
        device.last_seen = latest.created_at if latest else device.last_seen
        device.last_error = None if fresh else "No reading received in the last 2 minutes"
        db.commit()
        return {
            "ok": fresh,
            "detail": ("Last reading "
                       f"{(datetime.utcnow() - latest.created_at).seconds}s ago" if latest else "No readings yet"),
            "latest_value": latest.value if latest else None,
        }

    import cv2

    source: int | str = device.source or 0
    if device.source_type == "webcam":
        try:
            source = int(device.source or "0")
        except ValueError:
            source = 0

    started = time.perf_counter()
    cap = cv2.VideoCapture(source)
    ok, frame = cap.read() if cap.isOpened() else (False, None)
    latency_ms = round((time.perf_counter() - started) * 1000)
    cap.release()

    if not ok or frame is None:
        device.status = "offline"
        device.last_error = f"Could not open/read source ({device.source_type}: {device.source})"
        db.commit()
        return {"ok": False, "latency_ms": latency_ms, "detail": device.last_error}

    h, w = frame.shape[:2]
    scale = 480 / max(w, 1)
    if scale < 1:
        frame = cv2.resize(frame, (int(w * scale), int(h * scale)))
    _, buf = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, 75])
    device.status = "online"
    device.last_seen = datetime.utcnow()
    device.last_error = None
    db.commit()
    return {
        "ok": True,
        "latency_ms": latency_ms,
        "width": w,
        "height": h,
        "snapshot": "data:image/jpeg;base64," + base64.b64encode(buf.tobytes()).decode(),
    }


class ReadingIn(BaseModel):
    device_id: str
    value: float
    metric: str | None = None  # defaults to the device's registered metric


@router.post("/iot/readings")
def ingest_reading(body: ReadingIn, db: Session = Depends(get_db)):
    """The pluggable-IoT ingest: any device that can POST JSON can feed the platform."""
    device = db.query(Device).filter_by(id=uuid.UUID(body.device_id)).one_or_none()
    if device is None:
        raise HTTPException(status_code=404, detail="device not found")
    reading = SensorReading(device_id=device.id, metric=body.metric or device.metric or "value",
                            value=body.value)
    device.status = "online"
    device.last_seen = datetime.utcnow()
    device.last_error = None
    db.add(reading)
    db.commit()
    return {"ok": True}


@router.get("/devices/{device_id}/readings")
def device_readings(device_id: str, limit: int = 40, db: Session = Depends(get_db)):
    rows = (db.query(SensorReading).filter_by(device_id=uuid.UUID(device_id))
            .order_by(SensorReading.created_at.desc()).limit(limit).all())
    rows.reverse()
    return [{"value": r.value, "metric": r.metric, "at": r.created_at.isoformat() + "Z"} for r in rows]


# --- simulated sensors -------------------------------------------------------------
# Devices registered with source_type "simulated" get a reading every few seconds from
# this thread -- same ingest path and tables as real hardware, just a synthetic origin,
# so the Devices/live views demo with moving data out of the box.

_SIM_PROFILES = {
    "gas_ppm": {"base": 12.0, "amp": 6.0, "noise": 1.5},
    "temp_c": {"base": 84.0, "amp": 4.0, "noise": 0.8},
    "pressure_kpa": {"base": 2705.0, "amp": 30.0, "noise": 8.0},
}


def _simulator_loop(interval_s: float = 5.0):
    import math
    import random

    t0 = time.time()
    while True:
        try:
            db = SessionLocal()
            sims = db.query(Device).filter_by(kind="sensor", source_type="simulated").all()
            phase = (time.time() - t0) / 120.0 * 2 * math.pi  # slow 2-minute cycle
            for i, d in enumerate(sims):
                profile = _SIM_PROFILES.get(d.metric or "", {"base": 50.0, "amp": 10.0, "noise": 2.0})
                value = (profile["base"] + profile["amp"] * math.sin(phase + i * 1.3)
                         + random.gauss(0, profile["noise"]))
                db.add(SensorReading(device_id=d.id, metric=d.metric or "value", value=round(value, 2)))
                d.status = "online"
                d.last_seen = datetime.utcnow()
            db.commit()
            db.close()
        except Exception:
            pass  # never let the demo thread die on a transient DB hiccup
        time.sleep(interval_s)


def start_simulator():
    thread = threading.Thread(target=_simulator_loop, daemon=True, name="iot-simulator")
    thread.start()
